name: LimitedLife
main: com.limited_life.Main
version: 1.0
api-version: 1.21.4
author: Olivia, Dylan
commands:
  set-lives:
    description: Manually set amount of lives for a player
    usage: /<command> <player> <lives>
    permission: op
  lives:
    description: See how many lives you have left
    usage: /<command>
