name: LimitedLife
main: com.limited_life.Main
version: 1.0
api-version: 1.21.4
authors: [Olivia, Dylan]
commands:
  freeze:
    description: Stop time progression
    usage: /<command>
    permission: op
  settime:
    description: Manually set amount of time for a player
    usage: /<command> <player> <seconds>
    permission: op
  unfreeze:
    description: Start time progression
    usage: /<command>
    permission: op
  giveminutes:
    description: Give some of your time left to someone else
    usage: /<command> <player> <minutes>
  time:
    description: See how long you have left
    usage: /<command>
