name: LimitedLife
main: com.limited_life.Main
version: 1.0
api-version: 1.21.8
authors: [Olivia, Dylan]
commands:
  freeze:
    description: Freeze timer
    usage: /<command>
    permission: op
  givetime:
    description: Adjust players time
    usage: /<command> <player> <type> <amount>
    permission: op
  settime:
    description: Set players time in seconds
    usage: /<command> <player> <seconds>
    permission: op
  unfreeze:
    description: Unfreeze timer
    usage: /<command>
    permission: op
